name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Action against gridX community example post
        uses: ./
        with:
          discourse_url: ${{secrets.DISCOURSE_URL}}
          discourse_post_id: ${{secrets.DISCOURSE_POST_ID}}
          discourse_api_key: ${{secrets.DISCOURSE_API_KEY}}
          discourse_api_user: ${{secrets.DISCOURSE_USER}}
          spec_file: ./petstore.yaml
